# Setup
title:               Mahrud Sayrafi
tagline:             Mahrud Sayrafi
description:         >- # this means to ignore newlines until "url:"
  I am mathematician working in commutative algebra and algebraic geometry.
url:                 https://mahrud.github.io
baseurl:             '' # the subpath of your site, e.g. /blog
gtag:                G-7X5TT5VW46 # Google Analytics 4 Tag

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme:

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for entries
collections:
  experiments:
    output: true
  teaching:
    output: true
  seminars:
    output: true
  journal:
    output: true
  drafts:
    output: true
  drp:
    output: true
  etc:
    output: true
  GradMoCCA:
    output: true
  M2Week:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  footnote_backlink: "&#x21a9;&#xfe0e;"
  enable_coderay: false
  math_engine: katex
  syntax_highlighter_opts:
    disable: true

# Exclusions from the final site
exclude:
  - vendor
  - Gemfile*
  - proof.gemspec
  - Makefile
  - TODO
  - _archive/
  - _drp/archive/
  - _teaching/archive/
  - static/reveal.js/
