# Setup
title:               Mahrud Sayrafi
tagline:             Mahrud Sayrafi @ School of Mathematics, UMN
description:         >- # this means to ignore newlines until "url:"
  I am a second year graduate student at the University of Minnesota
  studying commutative algebra and algebraic geometry.
url:                 http://math.umn.edu
baseurl:             '/~mahrud' # the subpath of your site, e.g. /blog
gtag:                UA-131373039-1 # Google Analytics Tag

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme:

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for entries
collections:
  teaching:
    output: true
  arts:
    output: true
  drp:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  footnote_backlink: "&#x21a9;&#xfe0e;"
  enable_coderay: false
  math_engine: katex

# Exclusions from the final site
exclude:
  - vendor
  - Gemfile*
  - proof.gemspec
  - Makefile
  - TODO
  - _archive
  - _drp/archive
  - _teaching/archive
